# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a76ea9efe350deba47b0c57976f31a7891e441128ad55e951386679541ddedc88f884777fe6d5cb7051a06a5d57d37191a185da30f2e20e370e2245ab619e1c6

test:
  secret_key_base: 20f68dfcce66598f8c5910c06c04f7458c03e962d9b2b77f09f973f3b59c295a5fdda5a7e7d7baca35ab1eac8fbabbe0eff0cb178cfb051fa9b5066f20d27c6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
